# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Artifactory Nuget Example
  displayName: 'Artifactory Nuget'
  
- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    artifactoryService: 'SolEng Artifactory Main'
    targetResolveRepo: 'azure-nuget'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryNuGet@2
  inputs:
    command: 'push'
    artifactoryService: 'SolEng Artifactory Main'
    targetDeployRepo: 'azure-nuget'
    pathToNupkg: '*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
  
  - task: ArtifactoryPublishBuildInfo@1
    inputs:
      artifactoryService: 'SolEng Artifactory Main'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
